### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by caglarenes** [Unity-Technologies/PostProcessing#201] opened 2017-06-06 18:55 UTC
##### What happened?

I can't make Android build. It's stucks at this screen.

I tested it with empty project. I only add post-processing folder and I didn't use any script.

![taslak](https://user-images.githubusercontent.com/14127437/26846544-a4a396e0-4b02-11e7-8bee-c4f373f56382.png)

I can make PC and OSX build without any problem.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 5.6.1p2
Unity 2017.1.b08

Windows 10 Anniversary
OSX Sierra

for Android Build

**Comment by DannyMcGillick** [comment] 2017-06-13 00:18
We had the exact same problem, and I can't find the legacy image effects for Unity 5.6 either. I hope someone responds to this bug soon, pretty big showstopper.

**Comment by caglarenes** [comment] 2017-06-13 14:03
I tried all Post-Processing packages, even beta ones. No hope. Maybe old Unity builds like 5.5 or 5.4 give us temporal solution.

**Comment by Chman** [comment] 2017-06-13 17:37
Duplicate of #39, #81 and #174.

**Closed by Chman** 2017-06-13 17:37 UTC
Labels: duplicate
