### ISSUE TITLE
When using Ambient Occlusion, the image gets white, ignoring scene colors.

### ISSUE THREAD

**Issue by galfaroth** [Unity-Technologies/PostProcessing#88] opened 2017-02-08 12:26 UTC
Hi, When I set intensity of AO to more than 0, the scene gets white and I see like a debug of AO on the scene - I see white screen and just darkened places.

**Comment by YaWK** [comment] 2017-02-08 23:51
same here - rendering with activated AO failed. I got this console output: _ColorCorrectionLookupEditor.cs(62,41): warning CS0618: `UnityEditor.TextureImporter.textureFormat' is obsolete: `textureFormat is not longer accessible at the TextureImporter level. For old 'simple' formats use the textureCompression property for the equivalent automatic choice (Uncompressed for TrueColor, Compressed and HQCommpressed for 16 bits). For platform specific formats use the [[PlatformTextureSettings]] API. Using this setter will setup various parameters to match the new automatic system as well possible. Getter will return the last value set.'_

**Comment by Chman** [comment] 2017-02-10 11:58
Duplicate of #16.

[Known issues](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues). This is fixed in 5.6.

@YaWK This error has nothing to do with this post-processing stack, this file isn't part of the package.

**Closed by Chman** 2017-02-10 11:58 UTC

**Comment by Dawid93** [comment] 2017-05-23 09:57
I've got this bug in Unity 2017.1.0b5
