### ISSUE TITLE
error CS0117 for numerous editor scripts

### ISSUE THREAD

**Issue by Ruiiner** [Unity-Technologies/PostProcessing#134] opened 2017-04-02 00:22 UTC
##### What happened?
I downloaded and imported the Post Processing Stack and I was met with 14 errors that are all related to CS0117. All of them start with "'Graphics' does not contain a definition for" and ends with either Blit or DrawTexture.
![ppstackerrors](https://cloud.githubusercontent.com/assets/26845847/24583469/e5d1a62a-1718-11e7-8958-20327024a8d4.png)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version 5.6, Windows 10, Standalone windows.

i've already tried deleting the files and reinstalling them several times. I've even tried to reinstall unity as well.

**Comment by Chman** [comment] 2017-04-02 08:22
[`Graphics`](https://docs.unity3d.com/ScriptReference/Graphics.html) is a core class of Unity. So either your installation is broken or another script in your project is shadowing the internal `Graphics` class (which would be very bad in any case). Please run a search in your project folder, this could be caused by an asset downloaded from the Asset Store. More often than not these aren't namespace'd correctly and class name collision occurs.

**Comment by Kink3d** [comment] 2017-04-03 09:26
Yea, most likely you have a script with a class called Graphics or Unity needs a reinstall. Either way not a PostFX issue. Closing.

**Closed by Kink3d** 2017-04-03 09:26 UTC
