### ISSUE TITLE
Changing Parameters at runtime?

### ISSUE THREAD

**Issue by Arnooby** [Unity-Technologies/PostProcessing#42] opened 2016-12-16 19:56 UTC
Hello!

I juste started using this asset and it is really amazing, and will make me gain a lot of time in my project with multiple cameras.

I just wanted to know however if there is a way to change the values of a PostProcessing Profile at runtime (in order to give the players the ability to enable/disable effects)? I couldn't find the doc about it...

**Comment by evan-erdos** [comment] 2016-12-17 08:29
I would like to know about this as well. Because some things are stored as structs, I had a hard time modifying any particular property, as I had to then provide replacements for all the other properties on the struct. I tried to make it do a hue shift by modifying [`BasicSettings`][], it was basically impossible to implement without providing all the other values, which is vexing. This is made worse by the fact that some of these structs are inside other structs, so to change the hue in [`BasicSettings`][], you'd also need to replace the whole [`Settings`][] struct, which is quite impractical. 

[`BasicSettings`]: <https://github.com/Unity-Technologies/PostProcessing/blob/master/PostProcessing/Runtime/Models/ColorGradingModel.cs#L80>
[`Settings`]: <https://github.com/Unity-Technologies/PostProcessing/blob/master/PostProcessing/Runtime/Models/ColorGradingModel.cs#L261>

**Comment by Chman** [comment] 2016-12-17 18:28
Duplicate of #11 (more info in this issue).
Also, you can use [this handy script](https://github.com/keijiro/PostProcessingUtilities) until we release a proper solution.

**Closed by Chman** 2016-12-17 18:28 UTC
Labels: duplicate
