### ISSUE TITLE
SSR on Xbox One throw RenderTexture.GenerateMips errors

### ISSUE THREAD

**Issue by exiin** [Unity-Technologies/PostProcessing#290] opened 2017-09-13 12:03 UTC
With the Post-processing stack on Xbox, I got that error every seconds in the editor:
RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).

Post-processing stack version v2 - Unity 2017.1.1p1, For Xbox One

**Comment by Chman** [comment] 2017-09-13 12:05
We noticed the same issue on 2017.2b10, we're working on a fix in the engine.

**Comment by exiin** [comment] 2017-09-13 12:07
Ok, ping me if you want me to test it out

**Comment by Chman** [comment] 2017-09-13 12:57
It's been fixed in the Unity codebase but you'll have to wait for a future patch version of Unity to get it. I'm leaving this opened for now as we still need to run some tests with it.

**Comment by Chman** [comment] 2017-09-13 13:59
I can confirm it's been fixed in the Unity codebase, it'll be backported to previous versions of Unity soon so you'll have to wait for a patch to get it. Leaving this opened for now as we need to run some tests.

**Comment by Kink3d** [comment] 2017-10-16 15:23
Hi,

This has now been fixed (as chman said) and is in 2017.2.0f and backported to 2017.1.2p1 (released 3 days ago).

Thanks for the help!

**Closed by Kink3d** 2017-10-16 15:23 UTC
Labels: bug

**Comment by SteveCrse** [comment] 2017-12-11 08:47
Hey there,

any chance the fix will be backported to 2017.1.1f1? We can't update because of the missing Nintendo Switch plugin, but would still like to use SSR, without PostProcessing cluttering our Resources.

Thanks!

**Comment by SteveCrse** [comment] 2017-12-11 08:48
Hey there,

any chance the fix will be backported to 2017.1.1f1? We can't update because of the missing Nintendo Switch plugin, but would still like to use SSR, without PostProcessing cluttering our Resources.

Or any workaround possibly?

Thanks!
