### ISSUE TITLE
Motion Blur fails in last commit (Apr 10)

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#147] opened 2017-04-10 14:27 UTC
Motion Blur fails in last commit possibly because the last AA code adjust.  On previous commit works fine. (click the image to see at 100%)

(Unity 5.6f03 - windows 7 - directx11 - linear - forward)

![sin titulo](https://cloud.githubusercontent.com/assets/17572350/24866493/deb3d774-1dcf-11e7-8626-ede1b3ff7c70.png)

**Comment by Kink3d** [comment] 2017-04-10 15:07
Hey,

Can you provide a reproduction project? In my tests motion blur is fine in the latest commit.

Thanks

**Comment by nestg** [comment] 2017-04-10 17:55
Hi, this is a reduce version of my project with only the objects required to show the problem http://www.mediafire.com/file/aevz3lod5bvkk12/escene.rar I not understand the nature of the problem, in old versions of my project with previous Post Processing Stack versions i not see this "fields" problem in the motion blur, possibly all is normal but before motion blur looks better in my project, this is a screenshot of the problem in the reduce project that i upload. Thanks.
![sin titulo2](https://cloud.githubusercontent.com/assets/17572350/24875157/ceb08ada-1dec-11e7-8887-2ef1ba533de8.png)

**Comment by Kink3d** [comment] 2017-04-12 12:15
Thanks for the project, these are key in debugging issues.

However in this case I cannot reproduce any problems.

Here is a screenshot of your setup with the previous commit:
![moblurproblemold](https://cloud.githubusercontent.com/assets/11135817/24956846/75dbfba6-1f81-11e7-9fed-91ec3d408f45.png)

And here is one with the current commit:
![moblurproblemnew](https://cloud.githubusercontent.com/assets/11135817/24956854/8109fa64-1f81-11e7-8b93-60f8ee1c314a.png)

I don't see any reduction in quality here. It should also be noted that in the project you sent you are using FXAA for anti-aliasing and no Depth of Field. In this case nothing in that commit is touching the code path you're using.

For reference, here is the same scene using TAA instead of FXAA:
![moblurproblemtaa](https://cloud.githubusercontent.com/assets/11135817/24956915/b6b67192-1f81-11e7-8cdb-c938a3f19aaa.png)

TAA generally helps greatly with the visual appearance of motion blur and we would recommend using it if you can. What target platform are you developing for? You have eye adaptation enabled so we assume it is desktop/console.

Obviously, I could have missed something here. Please let us know if that is the case, otherwise I don't see a bug :/

Regards

**Comment by nestg** [comment] 2017-04-12 12:28
I cant use referred render to apply TAA because mi graphic card is not very powerfull and my game runs under 30FPS but if before that finish my game i see that with forward render the problem is reduced i write in this issue thread, Thankyou very much.

**Comment by Kink3d** [comment] 2017-04-12 13:04
You're welcome.

For what its worth I would consider reducing cost elsewhere (like reducing sample count and disabling high precision in AO, and reducing the max size of the source file of the dirt texture used in bloom) in an effort to be able to use TAA. 

TAA works correctly with the forward renderer and should not be particularly expensive, especially considering you are already using motion blur (therefore you are already calculating motion vectors).

Thanks for the update, closing.

**Closed by Kink3d** 2017-04-12 13:04 UTC
Labels: info requested

**Comment by nestg** [comment] 2017-04-12 13:13
Wow, with TAA the "line fields" is near to dissapear, thankyou very much.

![sin titulo4](https://cloud.githubusercontent.com/assets/17572350/24959270/e730f1b4-1f57-11e7-9180-d658b49ccab4.png)
