### ISSUE TITLE
GLSL linker error on Android

### ISSUE THREAD

**Issue by debaetsd** [Unity-Technologies/PostProcessing#97] opened 2017-02-15 15:26 UTC
Using the eye adaptation on Android (Google Pixel running ES 3.1) gives a GLSL linker warning resulting in a crash

Unity 5.6.0b8

> --------- beginning of crash
02-15 16:14:53.021 20993 21018 E Unity   : -------- GLSL link error: Warning: barrier used in non-uniform control flowWarning: barrier used in non-uniform control flow
02-15 16:14:53.021 20993 21018 E Unity   : 
02-15 16:14:53.021 20993 21018 E Unity   : 
02-15 16:14:53.021 20993 21018 E Unity   :  
02-15 16:14:53.021 20993 21018 E Unity   : (Filename:  Line: 757)
02-15 16:14:53.021 20993 21018 E Unity   : 
02-15 16:14:53.021 20993 21018 E Unity   : ERROR: Unable to link compute shader!
02-15 16:14:53.021 20993 21018 E Unity   :  
02-15 16:14:53.021 20993 21018 E Unity   : (Filename:  Line: 2424)
02-15 16:14:53.021 20993 21018 E Unity   : 
02-15 16:14:53.069 20993 21018 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 21018 (Thread-17)
02-15 16:14:53.070   459   459 W         : debuggerd: handling request: pid=20993 uid=10113 gid=10113 tid=21018
02-15 16:14:53.160 21131 21131 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-15 16:14:53.160 21131 21131 F DEBUG   : Build fingerprint: 'google/sailfish/sailfish:7.1/NDE63V/3389651:user/release-keys'
02-15 16:14:53.160 21131 21131 F DEBUG   : Revision: '0'
02-15 16:14:53.160 21131 21131 F DEBUG   : ABI: 'arm'
02-15 16:14:53.160 21131 21131 F DEBUG   : pid: 20993, tid: 21018, name: Thread-17  >>> com.test.pptest <<<
02-15 16:14:53.160 21131 21131 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
02-15 16:14:53.160 21131 21131 F DEBUG   :     r0 d49a4d38  r1 ffffe944  r2 0000001b  r3 00000004
02-15 16:14:53.160 21131 21131 F DEBUG   :     r4 d20851c4  r5 d2083010  r6 bfabcb90  r7 00000000
02-15 16:14:53.160 21131 21131 F DEBUG   :     r8 d3574b18  r9 d3574af0  sl 00000000  fp d2085120
02-15 16:14:53.160 21131 21131 F DEBUG   :     ip 00000000  sp d12ff368  lr d3c31a5c  pc d3c31a74  cpsr 60000010
02-15 16:14:53.164 21131 21131 F DEBUG   : 
02-15 16:14:53.164 21131 21131 F DEBUG   : backtrace:
02-15 16:14:53.164 21131 21131 F DEBUG   :     #00 pc 0056ca74  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #01 pc 0057158c  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #02 pc 005585bc  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #03 pc 00558838  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #04 pc 005527a8  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #05 pc 003c3b68  /data/app/com.test.pptest-1/lib/arm/libunity.so
02-15 16:14:53.164 21131 21131 F DEBUG   :     #06 pc 00047003  /system/lib/libc.so (_ZL15__pthread_startPv+22)
02-15 16:14:53.164 21131 21131 F DEBUG   :     #07 pc 00019bdd  /system/lib/libc.so (__start_thread+6)

**Comment by Chman** [comment] 2017-02-15 15:33
Duplicate of #85.

**Closed by Chman** 2017-02-15 15:33 UTC
Labels: duplicate
