### ISSUE TITLE
Bloom, HDR and Emission doesn't work if Default Behavior Mode is set to 2D

### ISSUE THREAD

**Issue by inewland53** [Unity-Technologies/PostProcessing#459] opened 2018-02-11 14:30 UTC
##### What happened?
I noticed when using Bloom Effect, HDR and Emission Material wouldn't show up inside the Game View but would in the Scene View. Discovered that this was only the case for a project created as 2D. I went to Edit -> Project Settings -> Editor, changed Default Behavior Mode from 2D to 3D, restarted Unity and all was working as expected.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.3.0f3 - Noticed issue simply inside the editor

**Comment by Chman** [comment] 2018-02-12 09:32
Duplicate of #226, this is an engine issue. The [issue tracker](https://issuetracker.unity3d.com/issues/setting-default-behavior-mode-to-2d-breaks-hdr-rendering) says it's fixed but apparently it's not... I'll ping the 2D team but I would recommend you send an official bug report via Unity.

**Closed by Chman** 2018-02-12 09:32 UTC
