### ISSUE TITLE
Shader compile errors under Linux/Vulkan, Unity 5.6.0p1

### ISSUE THREAD

**Issue by hymerman** [Unity-Technologies/PostProcessing#157] opened 2017-04-19 09:15 UTC
##### What happened?

Building a standalone Linux player with auto graphics API, using Unity 5.6.0p1, gives two shader errors on the same line of the screen space reflection shader (using the 1.0.1 release):

    Shader error in 'Hidden/Post FX/Screen Space Reflection': '' : compilation terminated at line 141 (on vulkan)
    
    Compiling Vertex program
    Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP
    
    
    Shader error in 'Hidden/Post FX/Screen Space Reflection': 'z' : vector field selection out of range at line 141 (on vulkan)
    
    Compiling Vertex program
    Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP

There were no errors under Unity 5.6.0f3, and as far as I can see from the change log, there were no relevant changes to Vulkan shader compilation introduced with the patch. I'm not a graphics programmer and the errors look nonsensical to me (there's no 'z' on that line) so I can't see how to fix or work around this.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0p1
Host: Windows 7 & Windows 10
Target: Linux 32 bit standalone
PostProcessing version: 1.0.1

**Comment by Kink3d** [comment] 2017-04-19 11:31
Hi,

Thanks for the detailed report. The line numbers are off because the shader includes another file `ScreenSpaceRaytrace.cginc`. I asked the Vulkan developers and a fix was already made today (convenient timing). It will be getting backported to a 5.6 patch when its verified.

Ill leave this open and update here when the patch lands :)

**Comment by hymerman** [comment] 2017-04-19 11:54
Doh! Thanks! So it's a Unity bug rather than a PostProcessing plugin bug?

How did this slip through the net and get into a Unity patch release? I thought there was all sorts of automated testing against popular plugins - surely this is one of them? (sorry, not complaining, I'm just genuinely curious)

**Comment by Kink3d** [comment] 2017-04-19 12:18
Yea its a Vulkan implementation specific bug on the editor side.

No worries, doesnt read like a complaint. Right now we dont do full regression checks against every platform/API against every patch. I personally test everything (within reason) in this package against each major release but as Vulkan is currently experimental I dont test it every time (so many platforms/APIs/devices to cover).

As this package is still currently under heavy development we also dont have automated regression tests against it when building the editor (like we do with other engine side features).

**Comment by hymerman** [comment] 2017-04-19 13:12
Fair enough, that all makes sense! Thanks again.

What I'll do for now is disable Vulkan support and add a 'test everything on next Unity version' config to our CI to catch this kind of thing before upgrading.

**Comment by Dave29483** [comment] 2017-05-18 06:59
The same issue exists for openglcore on macOS. Currently have to run without SSR and can't use Metal instead as its an older iMac (2011)

**Comment by Dave29483** [comment] 2017-05-22 06:27
Issue resolved in Unity 2017.1b6. I can use SSR in Vulkan and openglcore now without issues. 5.6.1p1 is still an issue.

**Comment by Kink3d** [comment] 2017-06-16 11:00
Hey, sorry for lack of communication.

This is now fixed. It was verified (by someone else) against 5.6.1p2. I just checked it in 5.6.1p4 and can confirm its fixed.

**Closed by Kink3d** 2017-06-16 11:00 UTC
Labels: resolved

**Comment by AlbertMN** [comment] 2018-04-15 08:09
I have this issue in Unity 2017.3.1.1f1;

```
Shader error in 'Hidden/Post FX/FXAA': failed to open source file: 'Common.cginc' at line 12 (on d3d11)

Compiling Vertex program with GRAIN DITHERING
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
```

_I_ can't build due to this error (and 14 others Post Processing-related), but my friend can - same version of Unity, same game.
