### ISSUE TITLE
Rendering fails when AA disabled at runtime

### ISSUE THREAD

**Issue by TheMento** [Unity-Technologies/PostProcessing#94] opened 2017-02-11 02:05 UTC
I am working on a game that uses multiple cameras with post effects enabled. I added a setting to my pause menu that allows the user to change the antialiasing mode at runtime between FXAA, TAA, and no AA. I do this by taking an existing default fx profile and modifying it based on a dropdown menu.

The issue comes in when switching from either FXAA or TAA to no AA. If the AA starts disabled, both FXAA and TAA can be turned on, and both can be switched between with no problems. The only line of code in the function that disables AA is postFxProfile.antialiasing.enabled = false;
When I set it to true in the other functions which enable AA, it works fine, but when set to false it breaks.
![image](https://cloud.githubusercontent.com/assets/13921780/22850204/d1355034-efd3-11e6-942b-e7364d61597e.png)

It is also worth noting that if I re-enable some form of AA before I exit the menu, the camera will start working again.

**Comment by Kink3d** [comment] 2017-02-13 11:02
Hi,

Are you also using MSAA (Project Settings > Quality Settings)? Are you in Forward or Deferred rendering path? Is this 5.5.x? 

We have many issues in 5.5 with multiple cameras, MSAA etc. These are fixed in 5.6 but will not get backported as the fix is too large.

**Comment by TheMento** [comment] 2017-02-13 11:33
This happened with MSAA disabled in Quality Settings and using the deferred path in 5.5.1.

**Comment by Kink3d** [comment] 2017-02-13 12:10
Ok, can you send me a reproduction project (or some of it)? I don't need your game, only all the code which controls AA switch/enable/disable.

**Comment by Kink3d** [comment] 2017-03-13 11:11
Closing due to inactivity

**Closed by Kink3d** 2017-03-13 11:11 UTC
Labels: info requested
