### ISSUE TITLE
noiseTex: Argument cannot be null

### ISSUE THREAD

**Issue by webhaikal** [Unity-Technologies/PostProcessing#462] opened 2018-02-13 13:30 UTC
##### What happened?
This error is similar to #403,
I've checked the PostProcessResources file and none of it is null.

`ArgumentNullException: Argument cannot be null.
Parameter name: value
UnityEngine.MaterialPropertyBlock.SetTexture (Int32 nameID, UnityEngine.Texture value) (at C:/buildslave/unity/build/Runtime/Export/Graphics.cs:475)
UnityEngine.Rendering.PostProcessing.Dithering.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/Effects/Dithering.cs:31)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.RenderFinalPass (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, Int32 releaseTargetAfterUse) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:903)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:695)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:433)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:295)`
##### Post-processing stack version (v1, v2)?
V2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2, Android

**Comment by Chman** [comment] 2018-02-14 12:49
Duplicate of #403.

**Closed by Chman** 2018-02-14 12:49 UTC
