### ISSUE TITLE
[v1] Black Screen on First Start

### ISSUE THREAD

**Issue by justinwasilenko** [Unity-Technologies/PostProcessing#450] opened 2018-02-05 09:12 UTC
##### What happened?
When hitting play for the first time once loading the project screen is just black PostProcessing gives these errors. This is also happening to a few people when first starting my shipped game after a restart the problem seems to disappear.

```
[Exception] NullReferenceException: Object reference not set to an instance of an object
PostProcessingBehaviour.OnPreCull()    Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:111
110:   // Prepare context
-->111:   var context = m_Context.Reset();
112:   context.profile = profile;
113:   context.renderTextureFactory = m_RenderTextureFactory;

[Exception] NullReferenceException: Object reference not set to an instance of an object
PostProcessingBehaviour.TryExecuteCommandBuffer[BuiltinDebugViewsModel]()    Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:442
440:       where T : PostProcessingModel
441:   {
-->442:       if (component.active)
443:       {
444:           var cb = GetCommandBuffer<T>(component.GetCameraEvent(), component.GetName());

PostProcessingBehaviour.OnPreRender()    Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:166
165:   // Command buffer-based effects should be set-up here
-->166:   TryExecuteCommandBuffer(m_DebugViews);
167:   TryExecuteCommandBuffer(m_AmbientOcclusion);
168:   TryExecuteCommandBuffer(m_ScreenSpaceReflection);

[Exception] NullReferenceException: Object reference not set to an instance of an object
PostProcessingBehaviour.OnPostRender()    Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:180
178:           return;
-->180:       if (!m_RenderingInSceneView && m_Taa.active && !profile.debugViews.willInterrupt)
181:           m_Context.camera.ResetProjectionMatrix();
182:   }
```

##### Post-processing stack version (v1, v2)?
v1
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3p3, Windows 10, Standalone Windows, Oculus Rift.
Only have Color Grading, Ambient Occlusion, and Bloom turned on.

**Comment by justinwasilenko** [comment] 2018-02-05 20:42
After more testing. This is happening with Single Pass rendering and the Color Grading module enabled. Using Multipass rendering this does not happen.

**Comment by robbiesri** [comment] 2018-02-07 01:16
Single-pass is not supported on v1 😢

**Comment by justinwasilenko** [comment] 2018-02-07 08:03
Oh that's no good.

I should probably make my next issue then,. With V2. Can't turn modules on or off during runtime. Using the On/Off button or disabling the module in t he inspector or through code have no effect while running. Unity 2017.3p3, Windows 10, Standalone Windows, Oculus Rift.

**Comment by Chman** [comment] 2018-02-07 09:06
> Using the On/Off button or disabling the module in t he inspector or through code have no effect while running.

I'm not sure how this would happen, I just tried it here and it works fine (either via the inspector or scripting). Do you have a repro I could look at?

**Comment by justinwasilenko** [comment] 2018-02-07 12:55
I just setup a empty project to test this and can confirm it worked in my empty project. I then reset my real project to use v2. 
When I first installed v2 turning elements on and off worked. However when I ran this code it stopped working:

`using UnityEngine.Rendering.PostProcessing;
PostProcessVolume postProcessVolume;

    void Awake()
    {
        postProcessVolume = mainCamera.GetComponent<PostProcessVolume>();
    }

//Called from a button to toggle Bloom on and off in the UI
        public void SetBloom(float value)
    {
        Bloom mb = null;
        postProcessVolume.sharedProfile.TryGetSettings(out mb);

        if (mb != null)
        {
            BoolParameter b = new BoolParameter();
            b.value = false;
            mb.enabled = b;
        }
    }`

Once enabled is set to false I can't use the UI to toggle the fx. I am assuming I am doing something wrong with my script here.

**Comment by justinwasilenko** [comment] 2018-02-07 13:29
Ok my problem occurs when using 'enabled' switching enabled to false, I can't turn it back on. However using 'active' Gives me the functionality I am looking for.

Also when using Bloom in V2 with Single Pass enabled there is heavy flickering / ghosting. Not present using MultiPass rendering. Made a quick video: https://youtu.be/PbRNb4XQ2UE

**Comment by Chman** [comment] 2018-02-07 13:31
Yep, you're replacing the original parameter with a new instance. See my comment on #429. Optimally it should be `readonly` to avoid these kind of mistakes but because of how serialization works in Unity it would require an additional, separate getter for each parameter :/

**Comment by Chman** [comment] 2018-02-07 13:37
Note that `active` and `enabled` are quite different. `active` toggle the _override set_ as a whole (it doesn't put it on the stack) whereas `enabled` (which is the On/Off buttons in the inspector) allows you to explicitly override the enabled state of the effect itself (e.g. you have a big volume with vignette enabled and you want a smaller volume in it with a higher priority where vignette will be completely disabled).

We lack good, extensive documentation but it's currently in the work and will be soon available in the official Unity manual.

**Comment by justinwasilenko** [comment] 2018-02-07 13:39
Great, thanks for the responses I really appreciate it. Yeah documentation is lacking, so it takes some trial and error at the moment. 

Do you have any thoughts on the Bloom issue in v2? I didn't see that in V1 while using Singlepass.

**Comment by Chman** [comment] 2018-02-07 14:20
I'm not sure about the bloom issue, I'm not the VR expert. But this kind of flickering could be caused by sampling issues or a wrong target size when generating the bloom pyramid... I'll take a look and try to find out what's going on but it may take some time.

**Comment by robbiesri** [comment] 2018-02-08 22:23
@justinwasilenko Could you open a new issue to track the flickering?

**Comment by Chman** [comment] 2018-02-09 12:22
New issue at #454. Closing this one as single-pass stereo isn't supported on v1.

**Closed by Chman** 2018-02-09 12:22 UTC
