### ISSUE TITLE
Motion blur problem on V2 and V1 single pass in VR

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/PostProcessing#492] opened 2018-03-06 19:19 UTC
##### What happened?
Motion blur does not seem to work in:
- 2018.1.0b10
- Oculus SDK, Rift HMD
- OpenVR SDK, HTC Vive HMD
- V2 or V1 single pass
My V2 project uses a a global post process volume.

##### Post-processing stack version (v1, v2)?
v1 - 
- single pass: split image in each eye 
- multi pass: works fine

v2 - 
- single pass: motion blur seems to have no effect
- multi pass: motion blur seems to have no effect

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
standalone windows, 2018.1.0b10, DX11

**Comment by robbiesri** [comment] 2018-03-07 07:30
Motion Blur is not supported right now.  Might be worth leaving open in case someone wants to support it...

**Comment by Chman** [comment] 2018-03-07 09:07
Motion blur is [force-disabled](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/Effects/MotionBlur.cs#L26) in VR and we don't have any plan to support it right now.

The reason why it's explicitly disabled is that it is very puke-inducing in VR and it simply doesn't work visually speaking. You would basically get a similar result to what the older gen, low persistence VR displays exhibited (and it would be even worse because of all the screen-space motion blur artifacts). That's not how our eyes work, we don't turn our head and change our eye focus the same way you would with a mouse look.

The alternative scenario would be to have a VR specific motion blur that only applies to objects (no camera) and maxes to the persistence of the current HMD (2/3ms on good ones, which is very very low). But it would require specific changes in the render pipeline.

**Comment by jackpr-unity** [comment] 2018-03-07 23:25
Thanks for the clarification.  I will remove motion blur from the 2018.1 Full Test Pass.  I'll let you decide if you want to leave the issue open as a feature stub or not.

**Comment by Chman** [comment] 2018-03-08 08:26
I think it might be worth leaving it in the full test pass, just to make sure that it really doesn't do anything if it's enabled (in case some flag is changed and introduces a regression or whatever).

I'll close this as this is not something we have plans for. Maybe if there's a VR-specific render pipeline someday we'll play with it.

**Closed by Chman** 2018-03-08 08:26 UTC

**Comment by marijneken** [comment] 2020-01-06 16:01
May I kindly ask to reconsider this behavior @Chman?
I have a special case. I'm developing an application that is both VR-based and uses 2D screens. I would never consider using motion blur in the VR render, as I know all too well that's not how things should be done. But, on my 2D screens, I do want motion blur. The code now contains a simple test to see if VR is enabled and then decides to disable the effect (a notification in the Editor would be nice, it took me quite a while to realize what was happening).
So, wouldn't it be possible to check if the camera that the PostProcessing effect is rendering on, has stereo enabled and only THEN disable the motion blur effect? Or some other means of checking that we're not applying motion blur to a VR camera. I would greatly appreciate it.
