### ISSUE TITLE
Motion Blur doesn't work with transparent camera

### ISSUE THREAD

**Issue by bfod** [Unity-Technologies/PostProcessing#126] opened 2017-03-22 18:45 UTC
If you set the camera clear mode to Depth Only or Don't Clear, the motion blur produces a completely white screen. (Unity 5.5)

**Comment by bfod** [comment] 2017-03-23 01:07
+ on 5.6 it produces permanent blur

**Comment by bfod** [comment] 2017-03-23 01:10
I fixed it locally, by making a custom version of Unity's motion vector shader and multiplying the vectors by (1-depth). But that is obviously not the best solution so I won't check in a patch.

**Comment by Kink3d** [comment] 2017-03-27 11:55
I just tested this to make sure but everything is working as expected.

First, in 5.5 we have a known issue with multiple cameras and certain post-fx. This is why youre getting a white screen and unfortunately this cant be fixed. This is fixed in 5.6 but the camera refactor is too large to backport to 5.5.

In 5.6 multiple cameras and post-fx seems to be working as intended. Motion blur requires both color and depth buffers to calculate. If you dont clear them its going to draw incorrectly (usually it draws permanent blur that ends up as black). In Depth Only the blur should be relatively correct as long as the camera is rendering objects behind the blurring object that are writing to the depth buffer.

If you have a camera at a lower depth value that draws to every pixel in the color and depth buffers (rendering the world for example) then another camera drawing a blurring object (for example, a gun in a first person shooter) at a higher depth with either of those Clear Flags settings you should get the correct results, as the lower depth camera will clear both the buffers and write them again ready for the second camera to render the other objects and their blur.

If you think you have this set up correctly and are still having issues please send us a small reproduction project and we will look at this for you.

**Comment by bfod** [comment] 2017-03-27 12:21
Thanks. Yeah I now have it working on 5.6. Too bad about 5.5!

**Comment by Kink3d** [comment] 2017-03-31 10:33
It is indeed, hopefully 5.6 will treat you well :)

**Closed by Kink3d** 2017-03-31 10:33 UTC
Labels: info requested
