### ISSUE TITLE
Gap in SSR

### ISSUE THREAD

**Issue by FlaxenFlash** [Unity-Technologies/PostProcessing#74] opened 2017-01-19 17:45 UTC
Gaps appear in SSR output when you move further away from objects. I'm not sure if this is expected behaviour or not. The information that it would need to reflect does appear to be on screen and I don't think it is related to the max distance settings as it is still reflecting other things that are actually further away. Example below of the scene close up and then again further away with a gap in the reflection around the contact point between the reflecting surface and the terrain object.
![screen_1920x1080_2017-01-19_17-40-51](https://cloud.githubusercontent.com/assets/3677577/22118281/0757e328-de6f-11e6-84e2-5ef83f59d9c0.png)
![screen_1920x1080_2017-01-19_17-41-22](https://cloud.githubusercontent.com/assets/3677577/22118286/09afc730-de6f-11e6-947e-11c0ba474693.png)

**Comment by Kink3d** [comment] 2017-01-30 15:55
Hi,

Can you please provide a reproduction project for this as well as tell us your OS and graphics API? SSR is undergoing a major refactor at the moment and we are aware the current version is fiddly at best, but this may be fixable with the right settings :)

**Comment by FlaxenFlash** [comment] 2017-01-30 22:01
Running Windows 10, Unity 5.4.2, DX11, though the problem persists no matter what api I switch it to. I can't find any settings that effect it at all other than the distance between the camera and the point of reflection. I could fix it by scaling the whole scene down so that it is very small, but obviously that is not ideal. My main use case for this is reflections in outdoor scenes on large bodies of water so this issue comes up a lot. Here is a basic project that reproduces the issue
https://drive.google.com/open?id=0BzXquMEbGqUXNUN5WGl2dnYwZlk

**Comment by Kink3d** [comment] 2017-02-13 12:28
There is indeed no workaround to this. However, we are currently working on a new implementation of SSR so this version will not receive a fix. I have added an enhancement tag and will leave this open as a reminder to test this thoroughly on our new version.

**Comment by xinleng** [comment] 2017-02-21 12:57
is this not due to the fact that the max distance of SSR is capped at 300 ? I can't find anywhere to increase that cap. I have a large scene and the SSR is being clipped at the distance if the camera moves far back from scene objects. I know SSR is meant to be used with reflection probes but in my case, I need to rely on the SSR pretty much the whole way.

**Comment by FlaxenFlash** [comment] 2017-02-21 17:34
As I said in my original post the terrain that meets the waters edge is closer than the tree, but the tree still reflects and the terrain doesn't so clearly this is a separate issue from the max distance value. Changing the max distance value also doesn't effect the gap in my test until it is so short that it starts to make the tree disappear. If you think they should allow distances greater than 300 you should probably make a separate issue for that

**Comment by Kink3d** [comment] 2017-10-16 14:41
Fixed by V2 SSR

**Closed by Kink3d** 2017-10-16 14:41 UTC
Labels: enhancement
