### ISSUE TITLE
Vignette hurts in VR

### ISSUE THREAD

**Issue by jcowles** [Unity-Technologies/PostProcessing#466] opened 2018-02-15 07:34 UTC
##### What happened?
Turn on vignette, put on HMD, crank up the intensity, notice that it feels like your eyes are constantly crossing.

##### Post-processing stack version (v1, v2)?
v2 (I think?)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.3, standalone windows

**Comment by robbiesri** [comment] 2018-02-16 01:44
I think this is related to #421.  Is this with Single-pass Stereo?  And what headsets?  If it does sound like 421, please let me know, and I'll dupe this one over.

**Comment by jcowles** [comment] 2018-02-16 05:09
This was not single pass.
I was using a Vive.

**Comment by robbiesri** [comment] 2018-02-16 08:13
Hrm, I still think this is related to #421, because of the asymmetric projection matrices.

Marking as duplicate of #421

**Closed** 2018-02-16 08:14 UTC
