### ISSUE TITLE
[V2] Screen Space Reflections and Bloom Artifacts

### ISSUE THREAD

**Issue by Braveo** [Unity-Technologies/PostProcessing#325] opened 2017-10-11 01:57 UTC
##### What happened?
Bloom and Screen Space Reflections have many artifacts. On bloom, random parts of the screen randomly flicker shiny for no reason, and on SSR, any object that has smoothness set to 0 automatically flickers black.
##### Post-processing stack version (v1, v2)?
Post-processing stack v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1p1, Windows 10 Home, in editor and standalone Windows.
Specs: Intel Core i5 6500, Nvidia Geforce GTX 1060 FE, 8gb ddr4 RAM
![postprocessing](https://user-images.githubusercontent.com/23423003/31418733-b4620a6a-adec-11e7-96a8-df8e2146043e.gif)

**Comment by Kink3d** [comment] 2017-10-11 09:34
Hi,

This seems to be caused by NaNs in the framebuffer, probably from your volumetric lights. Weve seen this bloom issue many times before, but I havent seen the SSR problem yet. 

Have you tried enabling "Stop NaN Propogation" on the PostProcessLayer component? This _should_ fix the problem.

Thanks

**Comment by Braveo** [comment] 2017-10-13 01:19
I've enabled it and it didn't fix the problem, SSR and Bloom still acts like that.

**Comment by Kink3d** [comment] 2017-10-16 15:16
Ok thanks. Does it still reproduce without Volumetric lights? What Volumetric light pack is that?

**Comment by Braveo** [comment] 2017-10-17 04:07
Without volumetric lights as well, here's the link to it: https://github.com/SlightlyMad/VolumetricLights

**Comment by tstobierski** [comment] 2017-11-04 12:52
In my project I found that SSR handles alpha in input buffer different way and breaks. It takes CameraTarget as input. In HDR there might be some pretty unlimited values in alpha channel. I use CamTarget alpha to store values for my UBER shader - encoded from int bits to half (using f16tof32() and vice versa). The SSR indeed goes bonkers (alpha values can be like 999999563798456 if we treat then as half).

This gives a hint that these crazy black artifacts comes from camera target alpha. It's also used to blend transparent particles. Alpha channel is not clamped 0..1 in HDR and I can imagine some shaders could cause accumulation of values in CamTarget buffer.

This is a potential hint you could check and maybe this will fix the issues for others. For me it was as simple as zeroying CamTarget alpha channel in deferred lighting pass to remove values I used (I copy them earlier and decode using additional RHalf texture).

**Comment by f1ac** [comment] 2017-12-16 19:19
Most recent v2 still has this issue, "Stop NaN Propogation" doesn't help. In my case it is caused by a NaN value in a custom procedural skybox.
![bloom_on_nan](https://user-images.githubusercontent.com/13987066/34073657-c94d17f0-e2a6-11e7-9866-95d576abca80.PNG)

**Comment by f1ac** [comment] 2017-12-16 19:55
The same single NaN pixel causing SSR to output NaNs on geometry + bloom around all the NaNs:
![ssr_bloom_on_nan](https://user-images.githubusercontent.com/13987066/34073838-d2b0558c-e2ab-11e7-9cfc-8f879b3adcbd.PNG)

**Comment by mmalek06** [comment] 2018-01-12 20:15
Hi there,
Soooo is anyone looking into this? In my case HDR on camera + bloom causes white blobs flickering on the screen where a lightsource is.

**Comment by Chman** [comment] 2018-02-05 13:02
Latest commit (b40105b) should fix the Stop NaN propagation feature and properly kill NaNs before postfx. Note that this won't fix the source issue (which is that you have NaNs in your framebuffer before post-processing is even applied).

**Closed** 2018-04-10 16:07 UTC
Labels: info requested
