### ISSUE TITLE
ArgumentException: Value does not fall within the expected range. SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.LanguageOf (SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit unit)

### ISSUE THREAD

**Issue by JeremyVansnick** [Unity-Technologies/PostProcessing#419] opened 2018-01-14 21:59 UTC
Visual Studio will not sync properly anymore whenever I have the processing stack 2 in my project.

Here's the Unity forum thread about this:
https://forum.unity.com/threads/visual-studio-wont-sync-anymore.511707/#post-3347243

Another person has shared he had the same problem upon installing the processing stack 2.

**Comment by danoli3** [comment] 2018-01-18 05:00
Try a Re-import all on your project assets.
Else look deeper to see if VS is having trouble creating sub projects. I find opening the project on my macbook laptop usually shows the core issue of the bridge problem... but you can probably find it in the editor logs.

Not an issue with PostProcessing.

**Comment by Chman** [comment] 2018-01-18 14:19
This potentially has to do with the assembly definition file that was added recently (and in all official open source Unity packages). This is not specific to Post-processing though so I'll close this, but I recommend you send a bug through the official bug reporting channel.

**Closed by Chman** 2018-01-18 14:19 UTC

**Comment by BluShine** [comment] 2018-02-11 03:06
Is there a workaround for this issue? Can you describe which "official bug reporting channel" you are referring to? Is there a reason this cannot be resolved by making a change to post-processing even if the issue is not specifically caused by the post-processing?

**Comment by Chman** [comment] 2018-02-12 08:43
We can't remove these files as they're needed for the package manager in 2018.1 (and PostProcessing is already in there). FWIW, a fix in Unity & VSTU is on its way (it may already have been released, but don't take my word on it).

**Comment by Duccem** [comment] 2018-06-25 21:11
I have the same problem, i have the VS 2017 community, and before the actualization it's worked ,After I updated to version 2018.1.6 the error appeared.
