### ISSUE TITLE
[v2] First time build shader error 

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#367] opened 2017-11-18 04:32 UTC
##### What happened?
First time build the game, many shader errors, but try again building will success.
![she](https://user-images.githubusercontent.com/18855621/32976884-3b19bb9c-cc5c-11e7-87d1-e38b727350fc.PNG)
![shw](https://user-images.githubusercontent.com/18855621/32976885-401defc8-cc5c-11e7-9467-083499f92321.PNG)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.2.0p1, standalone windows.

**Comment by Chman** [comment] 2017-11-18 06:39
Duplicate of #313.

**Closed by Chman** 2017-11-18 06:39 UTC
Labels: duplicate
