### ISSUE TITLE
Incorrect fog

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#141] opened 2017-04-07 05:03 UTC
Fog fog incorect in deffered rendering

Fog type Linear
Start value = 0
End value = 300

How it must looks(Global Fog) https://gyazo.com/922eef9a3df31e6ec9290b37610c2ce8
How it look with PostProccesing: https://gyazo.com/588939e22c268ea01b1a27fc610c0a22

ground and near objects are deffered, far objects are imposters and work with unity fog(opacity objects)

test in Editor unity 5.6

**Comment by Kink3d** [comment] 2017-04-10 15:54
Hi,

Can you provide a reproduction project? I cant reproduce any of this. 
What other effects are you using? What type of trees are they? This will be hard to debug with a project.

Thanks

**Comment by fdsagizi** [comment] 2017-04-11 05:33
Case 900429

**Comment by Kink3d** [comment] 2017-04-12 10:25
In the Fogbugz case this is listed as a problem with the Camera Preview window, is this correct?

I just tested it and neither Global for or the deferred fog in Post-processing stack work in the Camera Preview window as post-processing in general is not supported there.

Is this information correct. Your screenshots here suggest otherwise but their context isnt obvious.

**Comment by fdsagizi** [comment] 2017-04-13 04:42
1 hit Play in editor
2 Just select MainCamera, and swith from Forwad to Deffered and back - you will se defferences...

**Comment by Kink3d** [comment] 2017-04-13 09:29
In the camera preview window?

Yes, the difference is because post-processing is not supported in the camera preview window. You see fog there in forward because this fog is calculated in shader based on a global buffer. Post-processing fog is only applied to deferred rendered objects.

**Comment by fdsagizi** [comment] 2017-04-13 10:55
not a preview, - **game view** - just game view!

you will see deference, between normal work under Forward mode. And BUG if select Deferred mode.

IF use Global fog, in deferred render fog will be same as in Forwrad render.

**Comment by Kink3d** [comment] 2017-04-13 12:49
Actually, I find the opposite.

Post-processing - forward
![fog-pp-for](https://cloud.githubusercontent.com/assets/11135817/25005143/9569bab6-204f-11e7-98bd-250fb10db517.PNG)

Post-processing - deferred
![fog-pp-def](https://cloud.githubusercontent.com/assets/11135817/25005155/a435ae74-204f-11e7-9a7a-efd7ca69c4f6.PNG)

Global fog - forward
![fog-gf-for](https://cloud.githubusercontent.com/assets/11135817/25005164/ad0e5410-204f-11e7-8d79-612d72dd6d89.PNG)

Global fog - deferred
![fog-gf-def](https://cloud.githubusercontent.com/assets/11135817/25005174/b420ea06-204f-11e7-99c6-8b6badc1af33.PNG)

As you can see, when using Global Fog it is actually applied (incorrectly) on top of shader-based fog in forward.

The behaviour you are experiencing may be specific to your project. In which case if you could send us a project that reproduces this issue we will look at it for you.

Regards

**Comment by fdsagizi** [comment] 2017-04-14 10:55
https://gyazo.com/76c69bf7450cad057f00c2a0e9d680c8

please open sample in Case 900429

**Comment by Kink3d** [comment] 2017-04-18 16:04
Thanks,

Reproduced. Will look into fixing. For what its worth this doesnt reproduce with a start distance of 0. :)

**Comment by Kink3d** [comment] 2017-04-20 10:44
Fixed in latest master. Please update.

Thanks for reporting!

**Closed by Kink3d** 2017-04-20 10:44 UTC
Labels: bug
