### ISSUE TITLE
[V2]Weird bug with  SSR and bloom

### ISSUE THREAD

**Issue by Mrunpredictable** [Unity-Technologies/PostProcessing#440] opened 2018-01-30 05:46 UTC
I'm using Unity 2018.1.0b4 and i experienced this weird bug with Bloom and Screen Space Reflection 

Results
without SSR or Bloom
https://youtu.be/f-r1v-CAc4I

with SSR
https://youtu.be/eHgQ70Ze6c0

and with bloom
https://youtu.be/AMzyrySu-o8

**Comment by JohnManna** [comment] 2018-01-30 21:26
bloom bug looks to be the same as this: https://github.com/Unity-Technologies/PostProcessing/issues/356

**Comment by Mrunpredictable** [comment] 2018-01-31 07:35
It works fine with Stack V1 tho

**Comment by Chman** [comment] 2018-01-31 17:07
Do you have TAA enabled?

**Comment by Mrunpredictable** [comment] 2018-02-01 07:02
I deleted stack v2 and I'm currently using stack v1 but soon I will try it without Taa

**Comment by Chman** [comment] 2018-02-01 10:49
Did you update v2 before reimporting? Because we pushed a few fixes recently, and one that may help with dealing with NaNs like you saw. If you can reproduce it, please send us a repro-project! Because so far no one has (despite several people reporting similar issues) and we weren't able to reproduce it internally.

**Comment by Mrunpredictable** [comment] 2018-02-01 11:06
i downloaded the latest version today

**Comment by Chman** [comment] 2018-02-01 12:23
Ok so it's possible that 2782ec actually fixed it. I can't be 100% sure though. The only way to find out is to try again with the previous commit (before/after comparison)... If it's not too much to ask, do you think you could do that and report back?

**Comment by Mrunpredictable** [comment] 2018-02-01 13:01
Ok I will test that soon

**Comment by Mrunpredictable** [comment] 2018-02-01 14:34
i just tested d803468 but was not able to reproduce this bug

**Comment by Chman** [comment] 2018-02-05 13:01
b40105b should fix the NaN killer once and for all (famous last words). Note that this won't fix the origin of NaNs though.

**Closed** 2018-04-10 16:06 UTC
