### ISSUE TITLE
hard to access parameters via script

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#72] opened 2017-01-19 10:31 UTC
For example, if you want to change hueShift in ColorGrading, you have to create a super BIG struct called settings (which type is ColorGradingModel.Settings), then change settings.basic.hueShift, finally set it to ColorGrading.settings. All you want is changing a simple float value. It's not good for scripting and performance.

I have three solutions for this:
1. Like ParticleSystem, use a reference in every struct to remember which ParticleSystem instance it belongs to.
2. Define every single value in PostProcessingModel directly with out struct, or provide get&set.
3. Use class instead of struct.

**Comment by Chman** [comment] 2017-01-20 10:06
Duplicate of #11.

**Closed by Chman** 2017-01-20 10:06 UTC
