### ISSUE TITLE
[v2] Bloom causes flickering white blobs

### ISSUE THREAD

**Issue by Xefier** [Unity-Technologies/PostProcessing#219] opened 2017-07-20 04:24 UTC
##### What happened?
Just upgraded to Post Processing v2 and with bloom enabled I'm getting flickering white blobs that almost fill the entire screen at certain angles.
Post Processing v1 works perfectly (Noticed there is an "Anti-Flicker" feature in v1 but not v2)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.2f1
Windows 8.1 64-bit
Steam VR (Vive)

**Comment by Chman** [comment] 2017-07-20 08:11
Can we get a screenshot? Bloom reacts to what's on screen (and it does anti flickering in v2, it just doesn't do the initial median pass because it's quite expensive and incorrect as it directly modifies the bloom amount). So any bright spot you see is probably due to either having NaNs in your render or sudden ultra-high spec values.

**Comment by Xefier** [comment] 2017-07-20 17:05
Here is a couple screen shots, the white blobs randomly appear all over the screen at a very fast rate, in fact it took many tries to capture them.
Also attached the bloom settings I'm using.

![post process volume settings](https://user-images.githubusercontent.com/6353352/28429738-5f9a64b2-6d43-11e7-8884-8203e03d5b46.PNG)
![bloom blob1](https://user-images.githubusercontent.com/6353352/28429737-5f971ece-6d43-11e7-8ea2-31408f7b17d8.PNG)
![bloom blob2](https://user-images.githubusercontent.com/6353352/28429736-5f94d506-6d43-11e7-98e8-4c28a6a4828b.PNG)

**Comment by Chman** [comment] 2017-07-20 17:51
There's a very good chance these are caused by NaNs. See the dark pixels in the middle of each bloom "blobs"? They shouldn't be there :)

See my replies to #123 and #205, even though it's for DoF the issue is the same.

Do you use custom shaders or effects from the asset store?

**Comment by Xefier** [comment] 2017-07-20 18:08
First a reminder that this problem doesn't occur with Post Processing v1.
- Camera effect is only Post Processing v2
- Structure is Uber shader
- Terrain is RTP
- Sky is Time of Day
- Also using 2 Cameras
I'll try disabling these things one at a time to see if any of them are causing the issue.

**Comment by Chman** [comment] 2017-07-20 18:43
> First a reminder that this problem doesn't occur with Post Processing v1.

Because, like I said, bloom in v1 was actually doing something that it shouldn't be doing that crushed the NaNs (as a side effect) when it shouldn't. Making it correct actually made the underlying issue clearly visible :)

If you're having trouble identifying the issue you can send me a [RenderDoc capture](https://docs.unity3d.com/Manual/RenderDocIntegration.html), I'll take a peek at it.

**Comment by Xefier** [comment] 2017-07-20 19:59
Wasn't any of those things, it stops happening when I disabled MSAA. 
Turning off MSAA might be a temporary work around but still seems like a bug that needs to be fixed.

**Comment by Chman** [comment] 2017-07-20 20:12
Unless we can get a repro-case or a Renderdoc capture we won't be able to fix it if it's a bug on our side as we're not able to reproduce it. Please send either one of these so we can take a look.

**Comment by Chman** [comment] 2017-08-07 11:44
I added a NaN killer (enabled by default) to the stack. This will "solve" the "issue".

Once again, this isn't good practice and the faulty shader in your project should be fixed. For what it's worth, I've seen the "Uber shader" asset spit out NaNs more than once in the past...

**Closed by Chman** 2017-08-07 11:44 UTC
