### ISSUE TITLE
Exclude layers from Motion Blur

### ISSUE THREAD

**Issue by soma-web** [Unity-Technologies/PostProcessing#41] opened 2016-12-16 15:01 UTC
Will it be possible to exclude some layers from the motion blur?

**Comment by DuckyDuckling** [comment] 2016-12-16 22:42
Honestly a feature I would absolutely love to have support for natively aswell.

**Comment by Chman** [comment] 2016-12-17 18:30
You should already be able to [disable motion vectors](https://docs.unity3d.com/Manual/class-MeshRenderer.html) for meshes you don't want to apply motion blur too.

**Comment by soma-web** [comment] 2016-12-19 09:41
And how do I disable motion vecctors for particle systems

**Comment by Chman** [comment] 2016-12-19 10:13
Particle systems don't have motion vectors.

If I understand you well you want some of your objects not to have any motion blur and not be blurred either when another object with motion blur enabled goes in front of it ? That won't look right and isn't possible with the system in place. You could always try a multi-camera setup to do your own effect composition.

I'm curious, why do you need such a feature ? What's the use-case exactly ?

**Comment by soma-web** [comment] 2016-12-19 10:24
Hey, here is the case:

![mb](https://cloud.githubusercontent.com/assets/1823703/21309152/5bb0f93c-c5dd-11e6-8be2-60b536ef6ec8.png)
![without_mb](https://cloud.githubusercontent.com/assets/1823703/21309153/5bc6468e-c5dd-11e6-902d-c0d5a9748f60.png)

But we fixed it by giving the renderer of the particles a custom render queueu of 27,000 ;)

**Comment by Kink3d** [comment] 2017-01-03 15:32
Any value after the Opaque queue should do the job (3000+). However I dont know why youre having this issue and I cannot reproduce it on my end. Closing the issue, if you would like to discuss further please reopen.

**Closed by Kink3d** 2017-01-03 15:32 UTC
Labels: question
