### ISSUE TITLE
[V2] Temporal AA creates NaNs (or infinities?) when handling alpha blended particle shader

### ISSUE THREAD

**Issue by artyom-zuev** [Unity-Technologies/PostProcessing#340] opened 2017-10-21 05:22 UTC
##### What happened?
Using a particle shader on traditional geometry (for example, camera-facing quads produced by Vectrosity line renderer) results in NaNs (or infinities, not sure - it's a growing black blob, as usual with them) being rendered where multiple quads contribute to the same pixel. This is quite hard to explain, so I'm going to illustrate it. Here is geometry setup to trigger the issue:

![Image dissecting the geometry used to reproduce the issue](https://i.imgur.com/ShM4EX1.jpg)

And here is a long GIF showing how the source texture map looks on the Standard shader in opaque mode, how the issue appears once you render same geometry using Particles/Alpha Blended shader, and how the issue doesn't appear when Standard shader in Fade mode is used:

- https://i.imgur.com/WlLwTvU.gifv

I suspect it's an infinity caused by color from particle shader being added over and over again in TAA. I noticed for a while that every single additive and alpha blended particle shader started looking incorrect in V2 TAA, seemingly growing brighter and brighter every frame. This particular reproduction case might just trigger the infinity the fastest due to two pure white texels with almost no transparency being stacked on top of one another.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.4, Windows 10 Build 15063, PC project (DX11, HDR, linear, deferred)

**Comment by gregharding** [comment] 2017-10-21 05:26
That's pretty much what I found in my (updated) TAA issue: https://github.com/Unity-Technologies/PostProcessing/issues/337 - it breaks easily when the standard 'Particles/Alpha Blended' shader is used.

**Comment by artyom-zuev** [comment] 2017-10-21 05:33
Reproduced the issue with very barebones test case, should be simple to do that in an empty project. Just create a texture with pure white non-transparent areas (like a line depicted in the GIF below), map it to a quad, make two quads with material using that texture and position the camera in a way that makes white pixels of one quad overlap with white pixels of another quad. Voila, instant screen corruption:

![Short preview without shader inspector](https://i.imgur.com/Z4LCERy.gifv)

Full GIF showing how shaders are changed and moving the camera more:

- https://i.imgur.com/fKqhoWi.gifv

**Comment by artyom-zuev** [comment] 2017-10-21 09:25
Here is a temporary and clueless workaround that does nothing to prevent incorrect accumulation of particle shader fragments but seems to prevents infinity/NaN blobs from jumping out of the intersections like one in the test scene above: insert the following clamp to line 122 of TemporalAntialiasing.shader:

`color = float4 (min (color.x, 8), min (color.y, 8), min (color.z, 8), min (color.w, 8));`

Two bright particle texels stacked on top of each other would still remain black or otherwise incorrectly accumulate, but this seems to prevent the spread of the issue to the rest of the screen for now. I'd love to know how to fix this properly, though - blending of contributions from particle shaders seems completely broken, with every single frame multiplying the intensity.

**Comment by danoli3** [comment] 2017-10-24 05:28
+1 Found this issue also.

**Comment by Seathus** [comment] 2017-10-29 21:33
+1 Had this issue for a while also

**Comment by Chman** [comment] 2017-11-18 00:56
Duplicate of #337.

**Closed by Chman** 2017-11-18 00:56 UTC
Labels: duplicate
