### ISSUE TITLE
Bloom too intense on metal devices

### ISSUE THREAD

**Issue by overdub** [Unity-Technologies/PostProcessing#82] opened 2017-01-31 12:41 UTC
The Bloom effect ist about 4 times as bright on iOS metal than on desktop or OpenGL ES2.

**Comment by Chman** [comment] 2017-01-31 15:22
Potentially linked to #49 (precision issue).

**Comment by overdub** [comment] 2017-01-31 15:23
There are no shader compilation errors or warnings in xcode.

**Comment by Chman** [comment] 2017-01-31 15:33
If it's a precision error like #49 you won't see any error in the console (the error displayed in #49 is completely unrelated to the problem he's seeing, it's about motion vectors not being available on GLES2 - unrelated to Bloom).

**Comment by JohannesDeml** [comment] 2017-02-05 14:22
The effect you are describing might also be connected to #29. I'm noticing a larger (and also stronger) bloom on devices with large resolution. I wouldn't say it is 4 times as bright, but that might just happen if you tweaked your values to look good on a small resolution.

Otherwise I can't confirm the bug (Unity 5.5.1p1, but also no problems before (Tested since Unity 5.5 Beta 12 or something like that).

**Comment by inikitin** [comment] 2017-02-06 00:07
Same issue on macOS builds with Metal support.

**Comment by JohannesDeml** [comment] 2017-02-06 07:28
Hm, interesting. @overdub are you using gamma space as well? Maybe there is a problem with gamma space + Metal? Just a guess though ;)

**Comment by overdub** [comment] 2017-02-06 09:55
Yes, I also use gamma space. It really seems to be a precision issue: when replacing all halfs with floats in the shader and the cginc it goes away. Maybe that helps to narrow it down.

**Comment by Chman** [comment] 2017-02-10 12:04
I'm closing this as it is definitely a duplicate of #49. We're aware of the issue and we'll be looking into it soon.

**Closed by Chman** 2017-02-10 12:04 UTC
Labels: bug
