### ISSUE TITLE
(V2) AO problems with last commit

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#261] opened 2017-08-29 13:57 UTC
Hi, with last commit (Merge branch 'msvo' into v2) AO fails, AO effect appear, dissapear and work bad (the AO is incorrect), in the previous version work fine.  I use Unity 2017.1.p5 in windows 7.

**Comment by Chman** [comment] 2017-08-29 15:44
Could you check with the latest commit (27d139b)? MSVO was broken in forward on platforms without depth resolved available.

**Comment by nestg** [comment] 2017-08-29 19:02
Hi, the problem remain, this problem appear in "classic mode", when i use "modern mode" the AO dont flick but i prefer the quality of the old "classic mode", i use forward and linear rendering, thanks.

**Comment by Chman** [comment] 2017-08-29 20:10
I don't get any flickering with classic AO. What's your graphics card? Any chance you can share a small repro-project we can look at?

**Comment by nestg** [comment] 2017-08-29 21:00
I use a GT 740, this is a empty project that present the problem https://mega.nz/#!wvwDjbTT!JkiSwV9XAAfH59wlhr6qEmWLyydLPKNqSHvh_zOWQHw and this is a video of the problem https://mega.nz/#!RjolTTIQ!k8fTmbjkthsJZN8OUbvoWPSt75F2qOIa_S7N07jz120

**Comment by Chman** [comment] 2017-08-30 09:47
Indeed there was an issue with SAO in non-"ambient-only" mode... It should be fixed in d9de0d9. I tested against v2 before the MSVO merge and they look identical now.

**Comment by nestg** [comment] 2017-08-30 12:47
Hi, i download last commit and problems continue, i can resume this in 2.
1. The AO (classic mode) dissapear in the borders of the screen.
2. The AO (classic mode) dissapear when a other object is in front.
Looks like the flicker is fixed, for the moment i continue using a previous commit (august 21), thanks.

**Comment by Chman** [comment] 2017-08-30 13:01
I'm not sure I understand. Both versions work exactly the same here (pre-merge and using the latest commit). AO disappearing on the borders of the screen and when an object is in front is expected, AO is a screen-space effect, it doesn't know what's outside of the screen and doesn't have any backface information. It's always been like this, so I'm not sure about what you're experiencing and if it's at all related to what you think the "issue" is.

If you really do see a difference, please post two screenshots of the same scene with the exact same point of view using both version of AO, because I can't reproduce it on my side.

**Comment by nestg** [comment] 2017-08-30 13:14
You are right, I test news commits in my project and in this i am using Vignette effect and i cant see the AO borders issues, in the case of the objects in front happens some similar, when i update commit files in the project the AO have diferent parameters and is more strong, and the problem looks more intense, then for the moment all looks fine compared with old commits but would be fine if this 2 issues will be totally fixed in the future (AO wrong in borders and AO wrong behind objects), thankyou very much.

**Comment by Chman** [comment] 2017-08-30 14:14
As I said before, these two "issues" (AO border & backface) can't be fixed. It's a limitation of screen-space ambient occlusion techniques because you don't have access to backface information and anything outside of the screen. It is done entirely in _screen-space_. You can't do occlusion against something you don't know about.

**Closed by Chman** 2017-08-30 14:14 UTC
Labels: bug
