### ISSUE TITLE
Dithering local variable uberSheet == null keeps generating exceptions

### ISSUE THREAD

**Issue by khalv** [Unity-Technologies/PostProcessing#477] opened 2018-02-21 23:19 UTC
##### What happened?
Whenever i move the camera in the editor, i get this error:

ArgumentNullException: Argument cannot be null.
Parameter name: value
UnityEngine.MaterialPropertyBlock.SetTexture (Int32 nameID, UnityEngine.Texture value) (at C:/buildslave/unity/build/Runtime/Export/Graphics.cs:492)
UnityEngine.Rendering.PostProcessing.Dithering.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/Effects/Dithering.cs:31)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.RenderFinalPass (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, Int32 releaseTargetAfterUse) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:919)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:699)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:437)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:295)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

All i did was download the latest commit, add a post procecss layer to the camera, and a depth of field effect to a global volume. 

##### Post-processing stack version (v1, v2)?
 
V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

2017.3, Windows

**Comment by Chman** [comment] 2018-02-22 09:19
Duplicate of #467 (the underlying issue is the same, fix is coming).

**Closed by Chman** 2018-02-22 09:19 UTC
Labels: duplicate
