### ISSUE TITLE
Overrides affect profiles

### ISSUE THREAD

**Issue by readyplaygames** [Unity-Technologies/PostProcessing#254] opened 2017-08-19 01:59 UTC
##### What happened?
Changing anything on a Post Process Volume (say, increasing the intensity of the Grain) will change the underlying profile and not override the values. Is this intended?

##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.0p4, Win 7

**Comment by silentlamb1991** [comment] 2017-08-19 05:21
This is by design. All effect parameters stored in profiles not components. The "Overrides" UI behind volume is a shortcut to the profile.

**Comment by readyplaygames** [comment] 2017-08-19 06:26
Ah, I was confused by this on the "Quickstart" page:

"[The clone button] can be handy when you want to create quick variations
of [the] same profile (although you should really use the override system
if possible)."

I took that to mean that that specific volume would "override" the values
in the profile, like how a prefab works. What is the "override" system in
this case?

>

**Comment by silentlamb1991** [comment] 2017-08-19 14:03
In my understanding, "override" means "care", for example, a global volume "cares" bloom settings, and a local volume for a cave "cares" color grading settings to make a specific atmosphere. The global volume can "care" color grading too, in this case, you can use blend distance in local volume to blend color grading settings between local and global.

**Comment by Chman** [comment] 2017-08-21 11:28
Yes this is by design (for a multitude of reasons, [this comment](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/PostProcessVolume.cs#L6) gives a quick overview of why things are the way they are).

Profiles are assets, volume are just "profile holders" with a priority affected to them. "Overrides" are overrides in the global post-processing stack. Think of it as a stack where you pile up profiles ordered by priority. When the stack renders it will traverse the stack and settings on lower-priority volumes will be overridden by settings on higher priority ones, assuming they're marked as "overrides" (checkbox on the left of each setting). That's where the term "override" comes from. Once you start thinking of it as a true "stack" it makes a lot more sense.

> The global volume can "care" color grading too, in this case, you can use blend distance in local volume to blend color grading settings between local and global.

Note that you can also have multiple "global" profiles or varying priorities... It can be useful in a few cases. A global volume is _exactly_ the same as a local one, only difference is it's virtually "infinite" in the scene.

**Closed** 2017-08-31 11:51 UTC
