### ISSUE TITLE
[V2] Shader compiler error on Standalone Windows 64bit

### ISSUE THREAD

**Issue by Marbl70** [Unity-Technologies/PostProcessing#387] opened 2017-12-07 21:59 UTC
Shader error in 'Hidden/PostProcessing/DepthOfField': maximum temp register index exceeded at Assets/PostProcessing/Shaders/Builtins/DepthOfField.hlsl(175) (on d3d9)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA

Unity 2017.2.0p4, latest v2 post processing stack.

**Comment by Chman** [comment] 2017-12-08 10:13
Duplicate of #313.

**Closed by Chman** 2017-12-08 10:13 UTC
Labels: duplicate
