### ISSUE TITLE
RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).

### ISSUE THREAD

**Issue by pointcache** [Unity-Technologies/PostProcessing#373] opened 2017-11-23 10:57 UTC
When enabling reflections the console spams this message.
No additional info is given, and error is not clickable.
unity 2017.1.1.p3

**Comment by Chman** [comment] 2017-11-23 12:18
Duplicate of #290. Fixed in 2017.2.0f and backported to 2017.1.2p1.

**Closed by Chman** 2017-11-23 12:18 UTC
Labels: duplicate
