### ISSUE TITLE
Shader errors preventing build Shader error in 'Hidden/PostProcessing/AmbientOcclusion':

### ISSUE THREAD

**Issue by pointcache** [Unity-Technologies/PostProcessing#245] opened 2017-08-15 14:35 UTC
##### What happened?
getting these errors

`Shader error in 'Hidden/PostProcessing/AmbientOcclusion': unable to unroll loop, loop does not appear to terminate in a timely manner (322 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number at Assets/Addons/PostProcessing/Shaders/Builtins/AmbientOcclusion.hlsl(212) (on d3d9)

Compiling Fragment program with UNITY_COLORSPACE_GAMMA
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP
`

`Shader error in 'Hidden/PostProcessing/Debug/Waveform': in ps_3_0 uints can only be used with known-positive values, use int if possible at line 30 (on d3d9)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP
`

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
gpu nv980

2017.1f03 
Win 10 64
build target win64

Happens btw randomly, sometimes i can build many times in a row, then something happens and i cant build at all, no matter how much i try.

**Comment by pointcache** [comment] 2017-08-24 00:44
Mmmmm... 8 days later.. work I BOILING in unity

**Comment by robbiesri** [comment] 2017-08-24 07:13
Looks like a dupe of #230

**Comment by Chman** [comment] 2017-08-24 08:09
Yep thanks @robbiesri, it is indeed a duplicate.
@pointcache It should have been fixed already, please re-open this issue if you still experience this problem using the latest version.

**Closed by Chman** 2017-08-24 08:09 UTC
