### ISSUE TITLE
AO not compositing

### ISSUE THREAD

**Issue by Phantomx2** [Unity-Technologies/PostProcessing#75] opened 2017-01-19 20:16 UTC
AO shows like if it was in debug mode, it doesn't seem to multiply the render with the AO, but only shows AO.

![image](https://cloud.githubusercontent.com/assets/5246816/22123616/4b048dca-de5a-11e6-9c9c-1dd4df53a25d.png)

**Comment by Chman** [comment] 2017-01-20 10:08
Duplicate of #16.

**Closed by Chman** 2017-01-20 10:08 UTC
