### ISSUE TITLE
[V2] [2017.3.0f3] [XR] Effects not displaying in HMD when Single Pass Stereo is enabled

### ISSUE THREAD

**Issue by k0091601** [Unity-Technologies/PostProcessing#473] opened 2018-02-20 15:29 UTC
Effects not displaying in singlepass,

V2

2017.3.0f3 Windows 10 Vive

**Comment by Chman** [comment] 2018-02-21 16:12
Duplicate of #468.

**Closed by Chman** 2018-02-21 16:12 UTC
Labels: duplicate

**Comment by 01GOD** [comment] 2018-03-08 12:36
How was this closed? None of this functions properly in single pass stereo rendering on mobile VR. 

This issue is MAJORLY unresolved and is a MAJOR problem for the Unity mobile VR platform right now.

**Comment by Chman** [comment] 2018-03-08 12:40
Closed as a duplicate. Read the previous post.
