### ISSUE TITLE
Motion Blur doesn't disappear

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#80] opened 2017-01-29 10:25 UTC
Set transform via script the Motion Blur effect doesn't disappear, until re-enable the renderer.
(Unity version: 5.6.0b3)

Create a cube in runtime and modify the transform in inspector can also reproduce the bug.

**Comment by Kink3d** [comment] 2017-01-30 14:00
Hi,

I'm unable to reproduce this issue. Can you check that it still reproduces in the latest beta, and if so can you please upload a small reproduction project so we can take a look at it.

Thanks

**Comment by silentlamb1991** [comment] 2017-01-30 14:52
[Assets.zip](https://github.com/Unity-Technologies/PostProcessing/files/739226/Assets.zip)

Open the "Test" scene, import PostProcessing, run it, click mouse left button.

**Comment by Kink3d** [comment] 2017-01-30 15:34
Thanks, no idea why this wouldn't reproduce for me first time. This is a bug in our refactor to transform code in 5.6 editor. Ill open a ticket for this in Fogbugz as its not actually an issue with PostFX. I will post a link here for you for you to track the issue there then close this.

**Comment by Kink3d** [comment] 2017-01-30 16:00
Here is the issue for this in Fogbugz:

https://fogbugz.unity3d.com/f/cases/875948/

The problem should be fixed in a later Beta. Thanks for submitting :)

**Closed by Kink3d** 2017-01-30 16:00 UTC
Labels: info requested
