### ISSUE TITLE
(v2) SSR mipmap issue

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/PostProcessing#316] opened 2017-10-03 15:56 UTC
##### What happened?

When adding the SSR I got this message spamming the console:
`RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

##### Post-processing stack version (v1, v2)?
v2 lastest Commits on Oct 3, 2017

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.1p2, Windows 10, Windows Platform

**Comment by Chman** [comment] 2017-10-03 16:04
Duplicate of #290

**Closed by Chman** 2017-10-03 16:04 UTC
Labels: duplicate
